version: "3"
services:
  database:
    image: mariadb:10
    environment:
      - MYSQL_DATABASE=oneclass
      - MYSQL_USER=oneclass
      - MYSQL_PASSWORD=oneclass_pass
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - "./SQL_SCRIPTS/:/docker-entrypoint-initdb.d/"
  server:
    build: Docker/PHP
    ports:
      -  80:80
    environment:
      - DATABASE_HOST=database
      - DATABASE_NAME=oneclass
      - DATABASE_USERNAME=oneclass
      - DATABASE_PASSWORD=oneclass_pass
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ".:/var/www/html/"
    links:
      - database


